export const GET_ALL_SHOWS = 'GET_ALL_SHOWS';
export const SEARCH_MOVIE_BY_TITLE = 'SEARCH_MOVIE_BY_TITLE';

export const GET_SINGLE_SHOW = 'GET_SINGLE_SHOW';

export const GET_ALL_MOVIES_IN_WISHLIST = 'GET_ALL_MOVIES_IN_WISHLIST';
export const ADD_MOVIE_TO_WISHLIST = 'ADD_MOVIE_TO_WISHLIST';
export const CHECK_MOVIE_IN_WISHLIST = 'CHECK_MOVIE_IN_WISHLIST';